### ISSUE TITLE
Memory tests are failing against GLib >= 2.58 on cosmic

### ISSUE THREAD

**Issue by khurshid-alam** [ubports/unity-api#6]
On cosmic memory tests are failing against glib >= 2.58. They are getting SIGTRAP.  It compiles fine with GLib 2.56.

See the log here:

https://launchpadlibrarian.net/391831434/buildlog_ubuntu-cosmic-i386.unity-api_8.7+17.04.20170404-0ubuntu1+201810051321~ubuntu18.10.1_BUILDING.txt.gz

**Comment by dobey** [comment]
Which source are you actually building in this case? I think this is not an issue in the _bionic_ branch here on github, and it looks like you are simply rebuilding the last version which was released from Canonical, rather than the latest code from the branch here.

**Comment by khurshid-alam** [comment]
The source is this branch, 
https://code.launchpad.net/~khurshid-alam/unity-api/fix-build-cosmic

I updated the code. took few commits from here. It compiles on bionic (which has glib 2.56) fine but not in cosmic. 

Atm, I can't get debugging symbols installed on my machines, so I will try building directly from here and see if that works.

**Comment by dobey** [comment]
Yes, you've created and are maintaining your own fork there. You are not building with the code from this github repository. I'd strongly suggest rebasing against the _bionic_ branch in this github repository. I'd also suggest it's not a good use of time to be maintaining packages for non-LTS versions of Ubuntu, which only have 9 months of support. Tip of the _bionic_ branch should build against glib 2.58 on Ubuntu, as it's also being built on Arch already.

I think we can't really help you maintain your own custom fork of the project, in a different VCS on a different site.

If tip of the _bionic_ branch still has the tests failing due to a SIGTRAP, then please open a new issue, though I might suggest it's a glib problem if something that was working in 2.56 broke in 2.58.
